### ISSUE TITLE
Boilerplate no longer compiles

### ISSUE THREAD

**Issue by luskin** [looker/custom-action-hub-example#3]
Cloning this repo and doing a simple yarn install produces the following error:

```
Exit code: 1
Command: ./node_modules/.bin/tsc -d -p tsconfig.npm.json
Arguments: 
Directory: /Users/gregg/Code/looker-hubspot-actions/node_modules/looker-action-hub
Output:
src/hub/action_request.ts(4,35): error TS2497: This module can only be referenced with ECMAScript imports/exports by turning on the 'esModuleInterop' flag and referencing its default export.
src/server/server.ts(179,56): error TS2345: Argument of type 'ParsedQs' is not assignable to parameter of type '{ [key: string]: string; }'.
  Index signatures are incompatible.
```

This package additionally is requiring a node engine in `package.json` that is far outdated.

**Comment by luskin** [comment]
Upon further investigation it seems to be the `postinstall` script from the `looker-action-hub` package (which is just a copy of the github repository). Using `yarn install --ignore-scripts` worked to complete dependency installation however the server and hub imports are wrong, and when corrected, results in the following error:

```
yarn run v1.22.4
$ ./node_modules/.bin/ts-node ./src/index.ts
/Users/gregg/Code/looker-actions/node_modules/looker-action-hub/src/hub/index.ts:1
export * from "./action_form"
^^^^^^

SyntaxError: Unexpected token 'export'
    at Module._compile (internal/modules/cjs/loader.js:892:18)
    at Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/gregg/Code/looker-actions/node_modules/ts-node/src/index.ts:384:14)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/gregg/Code/looker-actions/src/action.ts:1:1)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Module.m._compile (/Users/gregg/Code/looker-actions/node_modules/ts-node/src/index.ts:392:23)
```

**Comment by murphpdx** [comment]
We're also running into this.
